name: Update Trashcar Data

on:
  schedule:
    - cron: '33 22 1 */3 *' # Every 3 months on the 1st

jobs:
  update_data:
    runs-on: ubuntu-latest
    name: Update Data
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: pip install requests flask

      - name: Fetch Trashcar Data
        run: python fetch_trashcar.py

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: |
            kv key put --binding data_trashcar data --path trashcar.json
            kv key put --binding data_trashcar info --path trashcar_info.json
